### ISSUE TITLE
New Update dropped 

### ISSUE THREAD

**Issue by Hizotaro** [MarceColl/zen-browser-flake#10]
Hey, just wanted to let you know that a new release is available:
https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.29

**Comment by beeb** [comment]
Would there be a way to automate this with nightly github actions or something similar? I understand that the build would sometimes fail if requirements change, but for most updates this would probably work.

**Comment by MarceColl** [comment]
Yes, will look into it at some point today if work is slow

**Comment by justDeeevin** [comment]
Fixed by #14?

**Comment by beeb** [comment]
@justDeeevin for me it didn't fix it

**Comment by justDeeevin** [comment]
I'm just talking about the version upgrade.

**Comment by beeb** [comment]
My bad I thought it was my issue ^^
