### ISSUE TITLE
Add note on 1Password integration to README

### ISSUE THREAD

**Issue by justDeeevin** [MarceColl/zen-browser-flake#12]
I'd make a PR but I want to hear from you about this.

It took me a while to figure out what process name I should put for this browser in `/etc/1password/custom_allowed_browsers` (see [this wiki article](https://nixos.wiki/wiki/1Password)). I eventually realized it's `.zen-wrapped`. I feel like this would be helpful to include in the README, since it isn't obvious. Alternatively, I would look into a way to make the actual process name something like `zen` or `zen-bin` and eliminate the necessity for this note in the first place.

Thoughts?

**Comment by MarceColl** [comment]
I'd add a note in the README, feel free to open a PR for it. Using `wrapProgram` I don't think there is much control over the final binary name without doing some post-processing and we want to keep `zen` and `zen-bin` for the wrapped programs and not the original binaries. It seems 1password uses the name of the final binary and we can't do much about it. I'd just add a section in the README to know about the interaction with 1password extension.
