### ISSUE TITLE
Desktop entry?

### ISSUE THREAD

**Issue by pective** [MarceColl/zen-browser-flake#2]
I love this browser, and this flake is great, but it would be great if it made a desktop entry, because opening the terminal and typing zen is kind of tedious

**Comment by MarceColl** [comment]
Hi, I added a desktop item but it doesn't have icons yet, will handle it tomorrow!

**Comment by MarceColl** [comment]
Actually just found out there are icons under the release tarball under a weird path (`/browser/chrome/icons/default/`), so used those and it seems to work. The release tarball doesn't have a desktop file so I copied the one they have in their repository and installed that.

Under my system it takes a re-login for desktop items to be detected so try that if it doesn't work after `sudo nixos-rebuild switch`.
