### ISSUE TITLE
flake out of date

### ISSUE THREAD

**Issue by ceselder** [MarceColl/zen-browser-flake#20]
alpha 32 launched

**Comment by justDeeevin** [comment]
closed by #22

wish more people put `fixes [ISSUE]` in commit descriptions so issues would auto-close

**Comment by callyral** [comment]
> closed by #22
> 
> wish more people put `fixes [ISSUE]` in commit descriptions so issues would auto-close

oh, i wasn't aware. i'll keep that in mind in case i make a PR again.
