### ISSUE TITLE
External links not opening

### ISSUE THREAD

**Issue by chakibchemso** [MarceColl/zen-browser-flake#41]
when i click on a link in the terminal it doesnt open in zen, even tho it does work for chromium if set as default.

**Comment by chakibchemso** [comment]
update: unityhub sign in button worked, and i signed successfully. maybe its a terminal thing?

**Comment by ch4og** [comment]
> when i click on a link in the terminal it doesnt open in zen, even tho it does work for chromium if set as default.

 I made a commit 1 hour before you've opened an issue that should fix that
https://github.com/MarceColl/zen-browser-flake/pull/40

**Comment by ch4og** [comment]
Make sure you are using latest flake and you did set zen as default application

**Comment by chakibchemso** [comment]
Indeed it works! had to delete the flake.lock file and rebuild. idk if that was necessary but it fixed the issue. thx
- oh and the set as default pop up appeared again after rebuild as you said.

**Comment by ch4og** [comment]
> had to delete the flake.lock file and rebuild

you never need to delete flake.lock, if you want to update it, just use `nix flake update`

**Comment by chakibchemso** [comment]
> > had to delete the flake.lock file and rebuild
> 
> you never need to delete flake.lock, if you want to update it, just use `nix flake update`

Thx for the tip 👍🏻 I'm very new especially to flakes. I think i should pay the experimental nix commands docs a visit.
